DELETE FROM Poblacion;
delete from sqlite_sequence where name='Poblacion';
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Muskiz", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Zierbana", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Getxo", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Sopela", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Ea", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Ispaster", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Lekeitio", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Mendexa", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Ondarroa", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Barrika", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Plentzia", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Gorliz", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Lemoiz", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Bakio", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Bermeo", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Mundaka", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Sukarrieta", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Busturia", 1);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId) VALUES(date('now'),"Ibarrangelu", 1);