DELETE FROM Poblacion;
delete from sqlite_sequence where name='Poblacion';
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Muskiz", 1,"poblaciones\bizkaia\Muskiz_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Zierbena", 1,"poblaciones\bizkaia\Zierbena_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Getxo", 1,"poblaciones\bizkaia\Getxo_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Sopela", 1,"poblaciones\bizkaia\Sopela_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Ea", 1,"poblaciones\bizkaia\Ea_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Ispaster", 1,"poblaciones\bizkaia\Ispaster_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Lekeitio", 1,"poblaciones\bizkaia\Lekeitio_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Mendexa", 1,"poblaciones\bizkaia\Mendexa_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Ondarroa", 1,"poblaciones\bizkaia\Ondarroa_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Barrika", 1,"poblaciones\bizkaia\Barrika_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Plentzia", 1,"poblaciones\bizkaia\Plentzia_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Gorliz", 1,"poblaciones\bizkaia\Gorliz_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Lemoiz", 1,"poblaciones\bizkaia\Lemoiz_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Bakio", 1,"poblaciones\bizkaia\Bakio_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Bermeo", 1,"poblaciones\bizkaia\Bermeo_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Mundaka", 1,"poblaciones\bizkaia\Mundaka_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Sukarrieta", 1,"poblaciones\bizkaia\Sukarrieta_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Busturia", 1,"poblaciones\bizkaia\Busturia_600px.png");
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI) VALUES(date('now'),"Ibarrangelu", 1,"poblaciones\bizkaia\Ibarrangelu_600px.png");