// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sandwitch.Infrastructure.Contexts;

#nullable disable

namespace Sandwitch.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251120074042_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Sandwitch.Domain.Entities.Arenal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Arenal");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.ArenalPoblacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArenalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoblacionId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ArenalId");

                    b.HasIndex("PoblacionId");

                    b.ToTable("ArenalPoblacion");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Bandera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Bandera");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("AltaMarAlba")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AltaMarOcaso")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArenalId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("BajaMarAlba")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("BajaMarOcaso")
                        .HasColumnType("TEXT");

                    b.Property<int>("BanderaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperatura")
                        .HasColumnType("REAL");

                    b.Property<double>("Velocidad")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("VientoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArenalId");

                    b.HasIndex("BanderaId");

                    b.HasIndex("VientoId");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Poblacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Poblacion");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Viento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Viento");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.ArenalPoblacion", b =>
                {
                    b.HasOne("Sandwitch.Domain.Entities.Arenal", "Arenal")
                        .WithMany("ArenalPoblaciones")
                        .HasForeignKey("ArenalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sandwitch.Domain.Entities.Poblacion", "Poblacion")
                        .WithMany("ArenalPoblaciones")
                        .HasForeignKey("PoblacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arenal");

                    b.Navigation("Poblacion");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Historico", b =>
                {
                    b.HasOne("Sandwitch.Domain.Entities.Arenal", "Arenal")
                        .WithMany("Historicos")
                        .HasForeignKey("ArenalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sandwitch.Domain.Entities.Bandera", "Bandera")
                        .WithMany("Historicos")
                        .HasForeignKey("BanderaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sandwitch.Domain.Entities.Viento", "Viento")
                        .WithMany("Historicos")
                        .HasForeignKey("VientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arenal");

                    b.Navigation("Bandera");

                    b.Navigation("Viento");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Poblacion", b =>
                {
                    b.HasOne("Sandwitch.Domain.Entities.Provincia", "Provincia")
                        .WithMany("Poblaciones")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Arenal", b =>
                {
                    b.Navigation("ArenalPoblaciones");

                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Bandera", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Poblacion", b =>
                {
                    b.Navigation("ArenalPoblaciones");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Provincia", b =>
                {
                    b.Navigation("Poblaciones");
                });

            modelBuilder.Entity("Sandwitch.Domain.Entities.Viento", b =>
                {
                    b.Navigation("Historicos");
                });
#pragma warning restore 612, 618
        }
    }
}
