DELETE FROM Poblacion;
delete from sqlite_sequence where name='Poblacion';
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Muskiz", 1,"/assets/img/poblaciones\bizkaia\Muskiz_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Zierbena", 1,"/assets/img/poblaciones\bizkaia\Zierbena_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Getxo", 1,"/assets/img/poblaciones\bizkaia\Getxo_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Sopela", 1,"/assets/img/poblaciones\bizkaia\Sopela_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Ea", 1,"/assets/img/poblaciones\bizkaia\Ea_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Ispaster", 1,"/assets/img/poblaciones\bizkaia\Ispaster_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Lekeitio", 1,"/assets/img/poblaciones\bizkaia\Lekeitio_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Mendexa", 1,"/assets/img/poblaciones\bizkaia\Mendexa_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Ondarroa", 1,"/assets/img/poblaciones\bizkaia\Ondarroa_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Barrika", 1,"/assets/img/poblaciones\bizkaia\Barrika_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Plentzia", 1,"/assets/img/poblaciones\bizkaia\Plentzia_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Gorliz", 1,"/assets/img/poblaciones\bizkaia\Gorliz_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Lemoiz", 1,"/assets/img/poblaciones\bizkaia\Lemoiz_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Bakio", 1,"/assets/img/poblaciones\bizkaia\Bakio_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Bermeo", 1,"/assets/img/poblaciones\bizkaia\Bermeo_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Mundaka", 1,"/assets/img/poblaciones\bizkaia\Mundaka_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Sukarrieta", 1,"/assets/img/poblaciones\bizkaia\Sukarrieta_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Busturia", 1,"/assets/img/poblaciones\bizkaia\Busturia_600px.png", false);
INSERT INTO Poblacion (LASTMODIFIED,NAME, ProvinciaId, IMAGEURI, DELETED) VALUES(datetime('now'),"Ibarrangelu", 1,"/assets/img/poblaciones\bizkaia\Ibarrangelu_600px.png", false);