name: Build & Test .NET API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Sandwitch.Service/Sandwitch.Service.csproj

    - name: Build project (no restore)
      run: dotnet build  ./Sandwitch.Service//Sandwitch.Service.csproj --no-restore

    - name: Run Tests (no build)
      run:  dotnet test ./Sandwitch.Service/Sandwitch.Test.Infrastructure/Sandwitch.Test.Infrastructure.csproj --no-build
