name: Build & Test .NET API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore solution dependencies
      run: dotnet restore ./Sandwitch.Service

    - name: Build solution     
      run: dotnet build  ./Sandwitch.Service --no-restore    

    - name: Run infrastructure tests      
      run:  dotnet test ./Sandwitch.Service/Sandwitch.Test.Infrastructure --no-build
