name: Build & Test .NET API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: Sandwitch.Service

jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 📥 Restore dependencies
        run: dotnet restore

      - name: 🧼 Clean project
        run: dotnet clean  

      - name: 🏗️ Build project
        run: dotnet build --no-restore    

      - name: ✅ Run tests      
        run:  dotnet test Sandwitch.Test.Infrastructure --no-build
